---

- name: "Setup | Update apt cache"
  become: yes
  become_user: "root"
  apt:
    update_cache: yes
    cache_valid_time: 86400
  ignore_errors: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "Setup | Install Dependencies"
  become: yes
  become_user: root
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - rsync
    - unzip